---
- name: Purge Logs Weblogic / PIA
  hosts: all
  vars:
    ansible_python_interpreter: /usr/bin/python3.6

    logs_path: /home/psadm2/psft/pt/8.61/webserv/peoplesoft/servers/PIA/logs
    jours_retention: 90

  tasks:

    - name: Chercher les logs de plus de {{ jours_retention }} jours
      ansible.builtin.find:
        paths: "{{ logs_path }}"
        age: "{{ jours_retention }}d"
        patterns:
          - "*.log.*"     
        recurse: true
      register: old_logs
      become: true
      become_user: psadm2

    - name: Afficher les fichiers trouvés
      ansible.builtin.debug:
        msg: "{{ old_logs.files | map(attribute='path') | list }}"

    
