---
- name: Trouver Python
  hosts: all
  gather_facts: false
  tasks:
    - name: Chercher tous les Python
      ansible.builtin.raw: ls /usr/bin/python* 2>&1
      register: r1
      failed_when: false

    - name: Afficher pythons disponibles
      ansible.builtin.debug:
        msg: "{{ r1.stdout_lines }}"

    - name: Chercher python3.12 partout
      ansible.builtin.raw: find / -name "python3.12" -type f 2>/dev/null
      register: r2
      failed_when: false

    - name: Afficher localisation python3.12
      ansible.builtin.debug:
        msg: "{{ r2.stdout_lines | default(['NON TROUVE']) }}"
