- name: Arrêter PeopleSoft
  hosts: all
  become: false

  tasks:
    - name: Arrêter PIA (PeopleSoft) en tant que psadm2
      ansible.builtin.shell: |
        cd /home/psadm2/psft/pt/8.61/webserv/peoplesoft/bin
        ./stopPIA.sh
      become: true
      become_user: psadm2
      register: stop_result

    - name: Afficher le résultat
      ansible.builtin.debug:
        msg: "{{ stop_result.stdout }}"
